// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACSr55CvldlJCxEZLpy3KKeLSLdLeeXKE',
    appId: '1:858038939565:web:083c32a48335e1e1c73b24',
    messagingSenderId: '858038939565',
    projectId: 'e-commerce-project-1-58026',
    authDomain: 'e-commerce-project-1-58026.firebaseapp.com',
    storageBucket: 'e-commerce-project-1-58026.firebasestorage.app',
    measurementId: 'G-XQVHYQ1HQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVBqufWPnpRzeiM5YDIOIzMMm2spR5JHM',
    appId: '1:858038939565:android:d2f4f3331294e261c73b24',
    messagingSenderId: '858038939565',
    projectId: 'e-commerce-project-1-58026',
    storageBucket: 'e-commerce-project-1-58026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3djiaPWCA_BblotvzFqY79dh4P1q5GjY',
    appId: '1:858038939565:ios:7f04655a723b9a65c73b24',
    messagingSenderId: '858038939565',
    projectId: 'e-commerce-project-1-58026',
    storageBucket: 'e-commerce-project-1-58026.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3djiaPWCA_BblotvzFqY79dh4P1q5GjY',
    appId: '1:858038939565:ios:7f04655a723b9a65c73b24',
    messagingSenderId: '858038939565',
    projectId: 'e-commerce-project-1-58026',
    storageBucket: 'e-commerce-project-1-58026.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACSr55CvldlJCxEZLpy3KKeLSLdLeeXKE',
    appId: '1:858038939565:web:a5181daf24e7ef04c73b24',
    messagingSenderId: '858038939565',
    projectId: 'e-commerce-project-1-58026',
    authDomain: 'e-commerce-project-1-58026.firebaseapp.com',
    storageBucket: 'e-commerce-project-1-58026.firebasestorage.app',
    measurementId: 'G-1TZ2SD6RQP',
  );
}
